name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Fly.io
      run: curl -L https://fly.io/install.sh | sh
      
    - name: Config Fly.io
      run : export FLYCTL_INSTALL="/home/runner/.fly" | export PATH="$FLYCTL_INSTALL/bin:$PATH"
    
    - name: Deploy Fly.io
      run: flyctl deploy -t ${{ secrets.ACCESS_TOKEN_FLY }}
