name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Fly.io
      run: curl -L https://fly.io/install.sh | sh
    
    - name: Deploy Fly.io
      run: FLYCTL_INSTALL="/home/runner/.fly" PATH="$FLYCTL_INSTALL/bin:$PATH" flyctl deploy -t ${{ secrets.ACCESS_TOKEN_FLY }}
